server:
  port: 9101

#person:
#  name: 张三
#  age: 20
#  birthday: 2021/12/22
#  maps:
#    k1: SSM
#    k2: SpringBoot
#  lists:
#    - Vue
#    - Layui
#    - ElmentUI
#  dog:
#    name: 旺财
#    age: 1
#  happy: true
#  springboot默认的数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/school?serverTimezone=UTC
#    指定druid连接池
#    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update #创建表或更新操作
    show-sql: true #开启控制台显示执行的SQL语句
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#  logging.level.org.springframework.boot.autoconfigure: error

  thymeleaf:
    prefix: "classpath:/templates/" #指定模板页面的路径
    suffix: .html #指定模板页面的后缀名
    mode: HTML5 #指定模板格式
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false

  mvc:
    static-path-pattern: static/**

  servlet:
    multipart:
    max-file-size: 20MB
    max-request-size: 20MB
  cache:
    redis:
      time-to-live: 60000 #设置缓存存储时间
  redis:
    host: 127.0.0.1 #redis服务器地址
    port: 6379 #redis服务器端口
    # password:  123456 #redis连接密码
    lettuce:
      pool:
        max-active: 8 #连接池最大连接数
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-idle: 8 #连接池中最大空闲连接
        min-idle: 0 #连接池中最小空闲连接

        #最大连接数   这个连接池能占有的最大数据库连接 ===> 当前连接池能占有的最大jdbc的连接
        #最小连接数： 这个连接池能一直数据库连接 ===> 一直保持的jdbc的连接
        #jdbc连接：

# 设置上传文件存储的路径
saveImage:
  path: D:/springdemo/src/main/resources/static

  # r56gzx0uk.hn-bkt.clouddn.com 域名

  # AK 8O4w2bmoOfLowwFc2qypuClurQwPD9dG5pVqOII-

  # SK jou3aVxQormg-sJs3mflgfvO2fkYvMCuuw6Evj1k

  # wr666 存储空间名称

# 七牛上传凭证
oss:
  qiniu:
    path: http://r56gzx0uk.hn-bkt.clouddn.com
    accessKey: 8O4w2bmoOfLowwFc2qypuClurQwPD9dG5pVqOII-
    secretKey: jou3aVxQormg-sJs3mflgfvO2fkYvMCuuw6Evj1k
    bucket: wr666